### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by eunzzae** [eunzzae/git-flow-practice#2]

**Comment by eunzzae** [comment]
## Tasks

- [ ] Print fizz, if is multiple of 3.
- [ ] print buzz, if is multiple of 5.
- [ ] print fizzbuzz if is multiple of 15.
- [ ] Otherwise, print i itself. 
## reference

- [Fizzbuzz wikipedia ](https://en.wikipedia.org/wiki/Fizz_buzz)
